apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops1
  labels:
    app: devops1
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: devops1
  template:
    metadata:
      labels:
        app: devops1
    spec:
      containers:
        - name: devops1
          image: ekanshmishra/devops-docker-image:latest
          ports:
            - containerPort: 8089 



---


apiVersion: v1
kind: Service
metadata:
  name: devops1-svc
spec:
  type: NodePort 
  selector:
    app: devops1
  ports:
  - port: 8089 
    targetPort: 8089
    nodeport: 30002
     
